---
title: "LMM"
author: "Davide Behr, Miriam Hu, Eugene Kahng, Sean Riordan, Syaza Senin, Jessica Toney"
date: "January 21, 2018"
output: pdf_document
---

```{r, include = FALSE}
library(knitr)
library(tidyverse)
library(lme4)

opts_chunk$set(echo = FALSE,
               cache = TRUE, autodep = TRUE,
               message = FALSE, warning = FALSE)
options(show.signif.stars = FALSE)
```

```{r load-data}
politeness <- read.csv("http://www.bodowinter.com/tutorial/politeness_data.csv")
```

```{r linear-model}
linear.model <- lm(frequency ~ ., data = politeness)
```

```{r lmm}
lmm.random.int <- lmer(frequency ~ attitude + gender + (1|subject) + (1|scenario), REML = FALSE, data = politeness)

lmm.random.int.random.slope <- lmer(frequency ~ attitude + gender + (1+attitude|subject) + (1+attitude|scenario), REML = FALSE, data = politeness)
```

```{r interpretations}

null.model <- lmer(frequency ~ gender + (1+attitude|subject) + (1+attitude|scenario), data = politeness, REML = FALSE)

summary(lmm.random.int.random.slope)

anova(model.null, lmm.random.int.random.slope)
```

